FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["ChatService/ChatService.csproj", "ChatService/"]

RUN dotnet restore "ChatService/ChatService.csproj"

COPY . .

WORKDIR "/src/ChatService"

RUN dotnet publish "ChatService.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "ChatService.dll"]
